source $VIMRUNTIME/vimrc_example.vim

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

" Buffers
set hidden

" Automatic indending
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set softtabstop=2

" Prettyfulness
set nu
set relativenumber
syntax on
set hlsearch
filetype on
filetype plugin on
filetype indent on

" Terminal
" set ff=unix

set backupdir=C:/vimtmp,.
set directory=C:/vimtmp,.
set noundofile

:imap jj <Esc>
:imap kk <Esc>

" mapping to <nop> means the key won't do anything
map <up> :bp<CR>
map <down> :bn<CR>
map <left> :bp<CR>
map <right> :bn<CR>

" set clipboard=unnamedplus

set mouse=a

set cursorline

match ErrorMsg '\%>120v.\+'